version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - aws --version
      - aws configure set region ap-southeast-1
      - wget https://dev.mysql.com/downloads/file/?id=500638

