version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - aws --version
      - aws configure set region ap-southeast-1
      - apt-get install mysql-client-5.5


