version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - whoami
      - java -version
      - npm install
      - mvn validate
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/java-tomcat-maven-example.war
    - appspec.yml
  discard-paths: yes
