version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      - apt update
      - apt install npm -y
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - npm install
      - mvn validate
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -e -Pdev clean package -DskipTests
artifacts:
  files:
    - target/java-tomcat-maven-example.war
    - appspec.yml
  discard-paths: yes
