version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - aws --version
      - aws configure set region ap-southeast-1
      - curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
      - dpkg -i mysql-apt-config*
      - apt update
      - apt install mysql-server -y


