#!/bin/bash
cp /opt/tomcat/webapps/java-tomcat-maven-example.war /opt/backs/
rm -rf /opt/tomcat/webapps/java-tomcat-maven-example.war
mysql -h venkey-$DATE.czrrfh9ifhyq.ap-southeast-1.rds.amazonaws.com -u admin -P 3306 -p12345678 > /opt/sql.txt

